# Generated by Django 4.2.7 on 2024-04-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='admission_charges',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='medication_charges',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='treatment_charges',
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='allergies',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
