# Generated by Django 4.2.7 on 2024-04-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_remove_medicalrecord_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=50)),
                ('appointment_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Appointment Fee')),
                ('admission_fee', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Admission Fee')),
                ('other_fees', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Other Fees')),
                ('pending', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
    ]
