# Generated by Django 4.2.7 on 2024-04-04 19:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0005_medicalrecord_billed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='reference',
        ),
        migrations.AddField(
            model_name='invoice',
            name='reference_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total Amount'),
        ),
        migrations.AddField(
            model_name='medicationcharge',
            name='billed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicationcharge',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medication_charges', to='records.invoice'),
        ),
        migrations.AddField(
            model_name='treatmentcharge',
            name='billed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentcharge',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_charges', to='records.invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='admission_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Admission Fee'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='appointment_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Appointment Fee'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='other_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Other Fees'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
