# Generated by Django 4.2.7 on 2024-04-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_invoice_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='billed',
            field=models.BooleanField(default=False),
        ),
    ]
