# Generated by Django 4.2.7 on 2024-04-02 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_schedule_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
    ]
