# Generated by Django 4.2.7 on 2024-02-09 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='patient',
            name='id_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=8, unique=True, verbose_name='ID Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Insurance Provider'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_record_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Medical Record Number'),
        ),
    ]
