# Generated by Django 4.2.7 on 2024-02-09 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0003_alter_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
