# Generated by Django 4.2.7 on 2024-02-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_patient_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcareprofessional',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of birth'),
        ),
        migrations.AlterField(
            model_name='healthcareprofessional',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='License number'),
        ),
    ]
